---

- name: install unzip
  yum:
    name: unzip
    state: present

- name: download consul
  get_url: 
    url: https://releases.hashicorp.com/consul/1.2.0/consul_1.2.0_linux_amd64.zip 
    dest: /var/tmp/consul_1.2.0_linux_amd64.zip 
    checksum: sha256:85d84ea3f6c68d52549a29b00fd0035f72c2eabff672ae46ca643cb407ef94b4

- name: unarchive consul
  unarchive:
    src: /var/tmp/consul_1.2.0_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes

- name: create consul user
  user:
    name: consul

- name: create consul data dir
  file:
    path: /tmp/consul
    state: directory
    owner: consul
    group: consul
    recurse: yes
    mode: 0777

- name: create consul config dir
  file:
    path: /etc/consul.d
    state: directory
    group: consul
    owner: consul
    recurse: yes
    mode: 0777



- set_fact: 
    private_ip: "{{ansible_eth0.ipv4['address']}}"
    node_name: "{{ansible_hostname}}"

- import_tasks: server.yml
  when: is_server

- import_tasks: agent.yml
  when: not is_server

- import_tasks: unitConfig.yml
