---

- name: Configure systemd unit
  copy:
    src: consul.service
    dest: /etc/systemd/system

- name: Template consult config
  template:
    src: consul.json.j2
    dest: /etc/consul.d/config.json

- name: enable consul service
  systemd:
    name: consul.service
    enabled: yes
    state: started