---

- name: install unzip
  yum:
    name: unzip
    state: present

- name: download consul
  get_url: 
    url: "{{consul_url}}"
    dest: "/var/tmp/consul_{{consul_version}}_linux_amd64.zip"
    checksum: sha256:{{consul_checksum}}

- name: unarchive consul
  unarchive:
    src: "/var/tmp/consul_{{consul_version}}_linux_amd64.zip"
    dest: /usr/bin
    remote_src: yes
