---

- name: download consul
  get_url: 
    url: https://releases.hashicorp.com/consul/1.2.0/consul_1.2.0_linux_amd64.zip 
    dest: /var/tmp/consul_1.2.0_linux_amd64.zip 
    checksum: sha256:85d84ea3f6c68d52549a29b00fd0035f72c2eabff672ae46ca643cb407ef94b4

- name: unarchive consul
  unarchive:
    src: /var/tmp/consul_1.2.0_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes
